;EASTERN PTO MODEL
;---------------------
AREAS       [CLFM.are]
OPTIMIZE    [CLFM.opt]
SCHEDULE    [CLFM.seq]
ACTIONS     [CLFM.act]
CONSTANTS   [CLFM.con]
CONTROL     [CLFM.run]
GRAPHICS    [CLFM.gra]
LANDSCAPE   [CLFM.lan]
LIFESPAN    [CLFM.lif]
REGIMES     [CLFM.rgm]
REPORTS     [CLFM.rep]
TRANSITIONS [CLFM.trn]

YIELDS      [CLFM.yld]

OUTPUTS     [CLFM.out]

LPSCHEDULE  [CLFM.LPS]